spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
mybatis:
  # 配置 mappe文件加载的位置
  mapper-locations: classpath:mappers/*Mapper.xml
  # 配置别名
  type-aliases-package: com.itheima.pojo
